/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MorphoAaveV3 } from "./MorphoAaveV3";
export * as factories from "./factories";
export { MorphoAaveV3__factory } from "./factories/MorphoAaveV3__factory";
